import { DayInform, MaintenanceRecord } from './types';

export const INITIAL_INFORMS: Record<string, DayInform> = {
  '2024-05-20': {
    date: '2024-05-20',
    title: '2024-05-20 정비 교대 인폼',
    author: '김철수 기사',
    activeShift: 'DAY',
    status: '진행 중',
    issueCount: 2,
    completionRate: 65,
    summary: 'A동 3번 컨베이어 벨트 모터 이상 소음 발생. 긴급 윤활유 주입 조치 완료. B동 배기 팬 필터 교체 예정.',
    lastSaved: '2024-05-20 14:30:15',
    records: [
      {
        id: 'rec-1',
        no: 1,
        date: '2024-05-20',
        time: '09:15',
        shift: 'DAY',
        equipmentId: 'EQ-A1-004',
        workDescription: '컨베이어 벨트 장력 조절 및 구동 모터 윤활유 보충',
        attachments: [
          {
            id: 'att-1',
            name: 'motor_check.jpg',
            type: 'image',
            size: '2.4 MB',
          },
        ],
        remarks: '정상 가동 확인',
        isRemarkWarning: false,
      },
      {
        id: 'rec-2',
        no: 2,
        date: '2024-05-20',
        time: '10:30',
        shift: 'DAY',
        equipmentId: 'EQ-B2-012',
        workDescription: '유압 프레스 압력 저하 점검, 밸브 씰 교체 예정',
        attachments: [],
        remarks: '부품 입고 대기 (내일 예정)',
        isRemarkWarning: true,
      },
      {
        id: 'rec-3',
        no: 3,
        date: '2024-05-20',
        time: '13:45',
        shift: 'DAY',
        equipmentId: 'EQ-C1-001',
        workDescription: '메인 서버실 항온항습기 필터 청소',
        attachments: [
          {
            id: 'att-2',
            name: 'filter_before_after.pdf',
            type: 'pdf',
            size: '1.1 MB',
          },
        ],
        remarks: '완료',
        isRemarkWarning: false,
      },
      {
        id: 'rec-4',
        no: 4,
        date: '2024-05-20',
        time: '14:20',
        shift: 'DAY',
        equipmentId: 'EQ-A2-008',
        workDescription: '로봇 암 센서 오작동 리셋 및 캘리브레이션',
        attachments: [],
        remarks: '특이사항 없음',
        isRemarkWarning: false,
      },
      {
        id: 'rec-5',
        no: 1,
        date: '2024-05-20',
        time: '16:10',
        shift: 'SW',
        equipmentId: 'EQ-C1-001',
        workDescription: '메인 서버실 항온항습기 2차 풍량 점검',
        attachments: [
          {
            id: 'att-3',
            name: 'filter.pdf',
            type: 'pdf',
            size: '850 KB',
          },
        ],
        remarks: '정상 풍량 유지 확인',
        isRemarkWarning: false,
      },
      {
        id: 'rec-6',
        no: 2,
        date: '2024-05-20',
        time: '17:40',
        shift: 'SW',
        equipmentId: 'EQ-A2-008',
        workDescription: '로봇 암 센서 오작동 리셋 및 캘리브레이션 후속 모니터링',
        attachments: [],
        remarks: '반복 오차 없음',
        isRemarkWarning: false,
      },
      {
        id: 'rec-7',
        no: 1,
        date: '2024-05-20',
        time: '23:30',
        shift: 'GY',
        equipmentId: 'EQ-B1-005',
        workDescription: '야간 조명 안정기 교체 작업 및 안전 차단기 테스트',
        attachments: [],
        remarks: '점등 테스트 완료',
        isRemarkWarning: false,
      },
    ],
    history: [
      {
        id: 'ver-3',
        timestamp: '2024-05-20 14:30:15',
        author: '김철수 기사',
        shift: 'DAY',
        summary: '로봇 암 센서 캘리브레이션 작업 및 부품 대기 상태 갱신',
        recordCount: 7,
        records: [],
      },
      {
        id: 'ver-2',
        timestamp: '2024-05-20 11:15:20',
        author: '김철수 기사',
        shift: 'DAY',
        summary: '유압 프레스 밸브 씰 교체 예정 및 첨부 파일 등록',
        recordCount: 4,
        records: [],
      },
      {
        id: 'ver-1',
        timestamp: '2024-05-20 08:30:00',
        author: '시스템 자동 생성',
        shift: 'DAY',
        summary: '당일 근무조 정비 인폼 템플릿 생성',
        recordCount: 1,
        records: [],
      },
    ],
  },
  '2024-10-25': {
    date: '2024-10-25',
    title: '2024-10-25 교대 인폼',
    author: '이영희 기사',
    activeShift: 'DAY',
    status: '이슈 있음',
    issueCount: 1,
    completionRate: 85,
    summary: '메인 컴프레서 1호기 과열 경보 발생. 라인 정지 후 점검 요망.',
    lastSaved: '2024-10-25 18:00:00',
    records: [
      {
        id: 'rec-101',
        no: 1,
        date: '2024-10-25',
        time: '10:15',
        shift: 'DAY',
        equipmentId: 'EQ-COMP-01',
        workDescription: '메인 컴프레서 1호기 과열 경보 발생. 라인 정지 후 냉각수 라인 점검 요망.',
        attachments: [
          {
            id: 'att-101',
            name: 'temp_alarm.log',
            type: 'document',
            size: '340 KB',
          },
        ],
        remarks: '메인 컴프레서 1호기 과열 경보 발생. 라인 정지 후 점검 요망.',
        isRemarkWarning: true,
      },
      {
        id: 'rec-102',
        no: 2,
        date: '2024-10-25',
        time: '14:20',
        shift: 'SW',
        equipmentId: 'EQ-LGT-C03',
        workDescription: 'C구역 조명 시스템 전체 점검 및 전구 15개 교체.',
        attachments: [],
        remarks: '전구 교체 완료',
        isRemarkWarning: false,
      },
      {
        id: 'rec-103',
        no: 3,
        date: '2024-10-25',
        time: '04:30',
        shift: 'GY',
        equipmentId: 'EQ-PUMP-02',
        workDescription: '냉각수 펌프 #2 압력 저하 확인. 예비 펌프로 전환 가동.',
        attachments: [
          {
            id: 'att-102',
            name: 'pump_switch.pdf',
            type: 'pdf',
            size: '1.2 MB',
          },
        ],
        remarks: '예비 펌프 정상 동작',
        isRemarkWarning: false,
      },
    ],
    history: [
      {
        id: 'ver-102',
        timestamp: '2024-10-25 18:00:00',
        author: '이영희 기사',
        shift: 'DAY',
        summary: '컴프레서 과열 보고서 등록',
        recordCount: 3,
        records: [],
      },
    ],
  },
  '2024-10-24': {
    date: '2024-10-24',
    title: '2024-10-24 교대 인폼',
    author: '최민수 기사',
    activeShift: 'GY',
    status: '승인됨',
    issueCount: 0,
    completionRate: 100,
    summary: '특이사항 없음. 전 라인 정기 순찰 완료 및 5S 점검 완료.',
    lastSaved: '2024-10-24 23:45:00',
    records: [
      {
        id: 'rec-201',
        no: 1,
        date: '2024-10-24',
        time: '22:00',
        shift: 'GY',
        equipmentId: 'EQ-SAFE-01',
        workDescription: '특이사항 없음. 심야 안전 점검 및 비상 정지 버튼 정상 작동 시험 완료.',
        attachments: [],
        remarks: '특이사항 없음',
        isRemarkWarning: false,
      },
    ],
    history: [
      {
        id: 'ver-201',
        timestamp: '2024-10-24 23:45:00',
        author: '최민수 기사',
        shift: 'GY',
        summary: '최종 승인 완료',
        recordCount: 1,
        records: [],
      },
    ],
  },
  '2023-10-25': {
    date: '2023-10-25',
    title: '2023-10-25 정기 점검 인폼',
    author: '김철수 기사',
    activeShift: 'DAY',
    status: '승인됨',
    issueCount: 0,
    completionRate: 100,
    summary: 'EQ-A1 모터 정기 윤활유 교체 및 캘리브레이션.',
    lastSaved: '2023-10-25 17:00:00',
    records: [
      {
        id: 'rec-301',
        no: 1,
        date: '2023-10-25',
        time: '11:00',
        shift: 'DAY',
        equipmentId: 'EQ-A1',
        workDescription: '정기 점검 및 메인 모터 윤활유 교체. 센서 캘리브레이션 재설정 완료.',
        attachments: [
          {
            id: 'att-301',
            name: 'report_oct.pdf',
            type: 'pdf',
            size: '1.8 MB',
          },
        ],
        remarks: '다음 점검일 조정 필요 (3개월 후)',
        isRemarkWarning: false,
      },
    ],
    history: [],
  },
  '2023-10-12': {
    date: '2023-10-12',
    title: '2023-10-12 긴급 정비 인폼',
    author: '박지성 기사',
    activeShift: 'DAY',
    status: '이슈 있음',
    issueCount: 1,
    completionRate: 90,
    summary: 'EQ-A1 릴레이 단락 긴급 부품 교체.',
    lastSaved: '2023-10-12 16:30:00',
    records: [
      {
        id: 'rec-401',
        no: 1,
        date: '2023-10-12',
        time: '13:10',
        shift: 'DAY',
        equipmentId: 'EQ-A1',
        workDescription: '긴급 정지 발생. 릴레이 스위치 단락 확인 및 부품(RS-402) 교체 진행.',
        attachments: [
          {
            id: 'att-401',
            name: 'error_log_img.jpg',
            type: 'image',
            size: '3.2 MB',
          },
        ],
        remarks: '라인 B 일시 중단 45분 소요',
        isRemarkWarning: true,
      },
    ],
    history: [],
  },
  '2023-09-05': {
    date: '2023-09-05',
    title: '2023-09-05 냉각기 인폼',
    author: '이영희 기사',
    activeShift: 'DAY',
    status: '승인됨',
    issueCount: 0,
    completionRate: 100,
    summary: 'EQ-A1 냉각 시스템 필터 청소.',
    lastSaved: '2023-09-05 15:20:00',
    records: [
      {
        id: 'rec-501',
        no: 1,
        date: '2023-09-05',
        time: '14:00',
        shift: 'DAY',
        equipmentId: 'EQ-A1',
        workDescription: '냉각 시스템 필터 청소 및 마모 부품 사전 점검. 이상 없음.',
        attachments: [],
        remarks: '-',
        isRemarkWarning: false,
      },
    ],
    history: [],
  },
  '2023-08-15': {
    date: '2023-08-15',
    title: '2023-08-15 도입 설치 인폼',
    author: '김철수 기사',
    activeShift: 'DAY',
    status: '승인됨',
    issueCount: 0,
    completionRate: 100,
    summary: 'EQ-A1 초기 도입 설치 및 시운전 완료.',
    lastSaved: '2023-08-15 17:30:00',
    records: [
      {
        id: 'rec-601',
        no: 1,
        date: '2023-08-15',
        time: '10:00',
        shift: 'DAY',
        equipmentId: 'EQ-A1',
        workDescription: '초기 도입 설치 및 시운전 완료. 성능 테스트 통과.',
        attachments: [
          {
            id: 'att-601',
            name: 'init_setup.pdf',
            type: 'pdf',
            size: '2.5 MB',
          },
          {
            id: 'att-602',
            name: 'warranty.pdf',
            type: 'pdf',
            size: '950 KB',
          },
        ],
        remarks: '벤더사(TechCorp) 엔지니어 동행',
        isRemarkWarning: false,
      },
    ],
    history: [],
  },
};

// Fill snapshot records for initial history
Object.values(INITIAL_INFORMS).forEach((inform) => {
  inform.history.forEach((snapshot) => {
    if (!snapshot.records || snapshot.records.length === 0) {
      snapshot.records = JSON.parse(JSON.stringify(inform.records));
    }
  });
});
